server:
  port: 8088
  ip: 0.0.0.0

middleware:
  mysql: bpics:bpics@tcp(192.168.1.88:3306)/bpics-v2?charset=utf8mb4&parseTime=True&loc=Local

log:
  path: ./logs

data:
  path: /opt/src/go/baipics-v2/data

md:
  path: 

templ: ./templ/*